services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: app-flux_control_api
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_IDE_CONFIG=serverName=127.0.0.1
    volumes:
      - ./src:/var/www
    networks:
      - flux_control_api

  nginx:
    image: nginx:alpine
    container_name: nginx-flux_control_api
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www
      - ./docker/local/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flux_control_api

networks:
  flux_control_api:
    driver: bridge
