# fly.toml app configuration file generated for api-flux-control on 2024-12-12T18:32:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-flux-control'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"
  [build.args]
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  CACHE_STORE = 'database'

  #DATABASE
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'postgres'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

# Main app VM
[[vm]]
  size = 'shared-cpu-1x'
  processes = ["app"]

# Queue worker VM
[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  processes = ["worker"]
  min_machines_running = 1
  group = "workers"

# Define processes
[processes]
  app = ""
  worker = "php artisan queue:work"

# Schedule to start machines at 9 AM BRT (12:00 UTC)
[[schedule]]
  cron = "0 12 * * 1-5"  # Monday to Friday at 12:00 UTC (9:00 AM BRT)
  action = "start"

# Schedule to stop machines at 7 PM BRT (22:00 UTC)
[[schedule]]
  cron = "0 22 * * 1-5"  # Monday to Friday at 22:00 UTC (7:00 PM BRT)
  action = "stop"
